[project]
name = "ai-dev-zoomcamp"
version = "0.1.0"
description = "AI Development Zoomcamp - Course Materials"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=5.2.9",
]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
    "ruff>=0.14.7",
]

